import 'package:mr_store_getx_firebase/features/shop/models/product_model.dart';

class ProductsDummyData {
  static final List<ProductModel> products = [
    ProductModel(
      id: 'cl001',
      title: 'T-Shirt',
      stock: 50,
      price: 20.00,
      salePrice: 15.00,
      thumbnail: 'assets/images/products/thmbnail_t-shirt.png',
      isFeatured: true,
      categoryId: '101',
      brandId: 'b010',
      description: 'Comfortable cotton t-shirt.',
      images: [
        'assets/images/products/red_t-shirt.png',
        'assets/images/products/white_t-shirt.png',
        'assets/images/products/green_t-shirt.png',
        'assets/images/products/blue_t-shirt.png',
      ],
      productType: 'Variation',
      productAttribute: [
        ProductAttributeModel(name: 'Size', values: ['S', 'M', 'L', 'XL']),
        ProductAttributeModel(
            name: 'Color', values: ['Red', 'Blue', 'Green', 'White']),
      ],
      productVariation: [
        ProductVariationModel(
          id: 'var001',
          sku: 'TS-RED-S',
          image: 'assets/images/products/red_t-shirt.png',
          price: 20.00,
          salePrice: 15.00,
          stock: 10,
          attributeValues: {'Color': 'Red', 'Size': 'S'},
        ),
        ProductVariationModel(
          id: 'var002',
          sku: 'TS-BLUE-M',
          image: 'assets/images/products/blue_t-shirt.png',
          price: 20.00,
          salePrice: 15.00,
          stock: 12,
          attributeValues: {'Color': 'Blue', 'Size': 'M'},
        ),
        ProductVariationModel(
          id: 'var003',
          sku: 'TS-GREEN-L',
          image: 'assets/images/products/green_t-shirt.png',
          price: 20.00,
          salePrice: 15.00,
          stock: 15,
          attributeValues: {'Color': 'Green', 'Size': 'L'},
        ),
        ProductVariationModel(
          id: 'var004',
          sku: 'TS-RED-XL',
          image: 'assets/images/products/white_t-shirt.png',
          price: 20.00,
          salePrice: 15.00,
          stock: 13,
          attributeValues: {'Color': 'White', 'Size': 'XL'},
        ),
      ],
    ),
    ProductModel(
      id: 'cl002',
      title: 'Jeans',
      stock: 40,
      price: 40.00,
      salePrice: 35.00,
      thumbnail: 'assets/images/products/thmbnail_jeans.png',
      isFeatured: true,
      categoryId: '102',
      brandId: 'b011',
      description: 'Stylish and durable denim jeans.',
      images: [
        'assets/images/products/black_jeans.png',
        'assets/images/products/blue_jeans.png',
      ],
      productType: 'Variation',
      productAttribute: [
        ProductAttributeModel(name: 'Size', values: ['34', '36']),
        ProductAttributeModel(name: 'Color', values: ['Black', 'Blue']),
      ],
      productVariation: [
        ProductVariationModel(
          id: 'var005',
          sku: 'JN-BLACK-30',
          image: 'assets/images/products/black_jeans.png',
          price: 40.00,
          salePrice: 35.00,
          stock: 8,
          attributeValues: {'Color': 'Black', 'Size': '30'},
        ),
        ProductVariationModel(
          id: 'var006',
          sku: 'JN-BLUE-32',
          image: 'assets/images/products/blue_jeans.png',
          price: 40.00,
          salePrice: 35.00,
          stock: 10,
          attributeValues: {'Color': 'Blue', 'Size': '32'},
        ),
      ],
    ),
    ProductModel(
      id: 'cl003',
      title: 'Jacket',
      stock: 30,
      price: 60.00,
      salePrice: 55.00,
      thumbnail: 'assets/images/products/jacket.png',
      isFeatured: true,
      categoryId: '103',
      brandId: 'b012',
      description: 'Warm and stylish winter jacket.',
      images: [],
      productType: 'Single',
      productAttribute: [],
      productVariation: [],
    ),
    ProductModel(
      id: 'cl004',
      title: 'Hoodie',
      stock: 40,
      price: 35.00,
      salePrice: 30.00,
      thumbnail: 'assets/images/products/hoodie.png',
      isFeatured: true,
      categoryId: '104',
      brandId: 'b013',
      description: 'Cozy hoodie for casual wear.',
      images: [],
      productType: 'Single',
      productAttribute: [],
      productVariation: [],
    ),
  ];
}
