// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5rbbmecVrHb0as8SUdQULtLW7p8nR5NQ',
    appId: '1:399858240534:web:55e601fddf532107f47937',
    messagingSenderId: '399858240534',
    projectId: 'mr-store-getx',
    authDomain: 'mr-store-getx.firebaseapp.com',
    storageBucket: 'mr-store-getx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChbZimtkpAJTlGJnrQUrv_mRZd1tbC6EY',
    appId: '1:399858240534:android:58976d51c395eb37f47937',
    messagingSenderId: '399858240534',
    projectId: 'mr-store-getx',
    storageBucket: 'mr-store-getx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeawc7SuxwgLoCOZu7TmAUFHtMuFMKWkE',
    appId: '1:399858240534:ios:5e877e6f02b7b95bf47937',
    messagingSenderId: '399858240534',
    projectId: 'mr-store-getx',
    storageBucket: 'mr-store-getx.firebasestorage.app',
    iosBundleId: 'com.example.mrStoreGetxFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeawc7SuxwgLoCOZu7TmAUFHtMuFMKWkE',
    appId: '1:399858240534:ios:5e877e6f02b7b95bf47937',
    messagingSenderId: '399858240534',
    projectId: 'mr-store-getx',
    storageBucket: 'mr-store-getx.firebasestorage.app',
    iosBundleId: 'com.example.mrStoreGetxFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5rbbmecVrHb0as8SUdQULtLW7p8nR5NQ',
    appId: '1:399858240534:web:deadad2aae5bfb68f47937',
    messagingSenderId: '399858240534',
    projectId: 'mr-store-getx',
    authDomain: 'mr-store-getx.firebaseapp.com',
    storageBucket: 'mr-store-getx.firebasestorage.app',
  );
}
