// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXDkqdaOhET7oiY6ShOoZ6EUxehjZ1BMs',
    appId: '1:110570371578:web:c6f71efd1fd9a4c1c2cc43',
    messagingSenderId: '110570371578',
    projectId: 'fir-ecommerce-customer',
    authDomain: 'fir-ecommerce-customer.firebaseapp.com',
    storageBucket: 'fir-ecommerce-customer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ1FfqeUmZ8k_kmCtYYEStgwozaG-7dco',
    appId: '1:110570371578:android:f476206659b9908ec2cc43',
    messagingSenderId: '110570371578',
    projectId: 'fir-ecommerce-customer',
    storageBucket: 'fir-ecommerce-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAKqMQlDLJE_UeGye62npqdOJYYuu59_k',
    appId: '1:110570371578:ios:5b0331dd6e9e8a80c2cc43',
    messagingSenderId: '110570371578',
    projectId: 'fir-ecommerce-customer',
    storageBucket: 'fir-ecommerce-customer.appspot.com',
    androidClientId: '110570371578-el3ka0g4n10ep5omb5s7t8r76objpl0g.apps.googleusercontent.com',
    iosClientId: '110570371578-0cpmvsjdjnbtcpqv6pth0toe1m0r10sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrStoreGetxFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAKqMQlDLJE_UeGye62npqdOJYYuu59_k',
    appId: '1:110570371578:ios:5b0331dd6e9e8a80c2cc43',
    messagingSenderId: '110570371578',
    projectId: 'fir-ecommerce-customer',
    storageBucket: 'fir-ecommerce-customer.appspot.com',
    androidClientId: '110570371578-el3ka0g4n10ep5omb5s7t8r76objpl0g.apps.googleusercontent.com',
    iosClientId: '110570371578-0cpmvsjdjnbtcpqv6pth0toe1m0r10sj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrStoreGetxFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXDkqdaOhET7oiY6ShOoZ6EUxehjZ1BMs',
    appId: '1:110570371578:web:b2b7b42cd8baf7ffc2cc43',
    messagingSenderId: '110570371578',
    projectId: 'fir-ecommerce-customer',
    authDomain: 'fir-ecommerce-customer.firebaseapp.com',
    storageBucket: 'fir-ecommerce-customer.appspot.com',
  );
}
